In [ ]:
#que1

In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [6]:
N=5
matrix=np.column_stack([x**(N-i-1) for i in range(N)]) 
matrix

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [5]:
N=7
matrix=np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)

[[    1     1     1     1     1     1     1]
 [   64    32    16     8     4     2     1]
 [  729   243    81    27     9     3     1]
 [ 4096  1024   256    64    16     4     1]
 [15625  3125   625   125    25     5     1]]


In [ ]:
# que2

In [10]:
def moving_average(x, w):
    return np.convolve(x, [1,1,1], 'valid') / w

data = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print(moving_average(data,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
